// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yzqigrjaairdpmadoqmk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inl6cWlncmphYWlyZHBtYWRvcW1rIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAwODA3NDgsImV4cCI6MjA2NTY1Njc0OH0.U_k7qZxHCiCtcb0k-oZrVW_X1CC7Dd1zkhH3ta2ZO7w";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);